name: Release
on:
  push:
    branches: ['main']
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
  workflow_dispatch:
permissions:
  contents: read
env:
  HUSKY: 0
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: lts/*
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm exec semantic-release
